### ISSUE TITLE
Commands problem in shop

### ISSUE THREAD

**Issue by haynesey** [itsnewtjam/newtShop-Issues#31]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Setup**
 - newtShop Version: 
 - newtLib Version: 
 - Spigot Version: 

**Additional context**

**Comment by itsnewtjam** [comment]
I'm not immediately sure why that'd be an issue, could you let me know if it still doesn't work in v2.0? Just pushed an update!

**Comment by haynesey** [comment]
Unfortuantely it still doesnt work, i assume this is because the categories config has changed its not recognising it, What coding will i need to put into it now?

As youve changed it slightly

items:
  BONE:
    buy: 50
    sell: 4
    item:
      type: NORMAL
      material: BONE

**Comment by itsnewtjam** [comment]
Yeah, category files got updated a bit in 2.0 to be a little more straightforward and a lot more future-proof. You can read about the new item format [on the docs here](https://docs.newtjam.com/newtshop/item-format/), or if you prefer a video version you can check the [2.0 overview video](https://www.youtube.com/watch?v=99UD0SUCd_4) where I also walkthrough the item format.

Specifically, your command item when adapted would look like so:
```yaml
COMMANDTRENCH:
  buy: 500000.0
  item:
    type: 'COMMAND'
    material: 'DIAMOND_PICKAXE'
    name: '&2&l3X3 &7&lTrench &2&lPickaxe'
    shop-lore:
      - '&7---------------'
      - '&d&lDigs a 3x3 Cuboid'
      - '&7---------------'
      - '&5&lUnbreakable'
      - '&7---------------'
    command: 'tools give @player@ 3x3trench_pickaxe'
```
